apiVersion: v1
kind: PersistentVolume
metadata:
  name: lucene-directory-volume
spec:
  capacity:
    storage: 200Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: lucene-directory-volume
    fsType: ext4
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: failure-domain.beta.kubernetes.io/zone
          operator: In
          values:
          - us-central1-a
          - us-central1-b
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lucene-directory-volume-pvc-rw
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-search
  labels:
    app: text-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: text-search
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: text-search
    spec:
      volumes:
        - name: security-data
          secret:
            secretName: service-account-key
        - name: lucene-directory-path
          persistentVolumeClaim:
            claimName: lucene-directory-volume-pvc-rw
      containers:
      - image: gcr.io/grocery-brasil-app/text-search
        name: text-search
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health/liveness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 10
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health/readiness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 10        
        volumeMounts:
          - mountPath: /var/secrets/google
            name: security-data
            readOnly: true
          - mountPath: /var/lucene-directory-volume
            name: lucene-directory-path
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/secrets/google/key.json
          - name: LUCENE_DIRECTORY_PATH
            value: file:///var/lucene-directory-volume/lucene_index_test
        ports:
          - containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            ephemeral-storage: 1Gi
            memory: 2Gi
          requests:
            cpu: 250m
            ephemeral-storage: 512Mi
            memory: 512Mi
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "text-search"
  namespace: "default"
  labels:
    app: "text-search"
spec:
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  selector:
    app: "text-search"
  type: "NodePort"
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: grocery-brasil-app-https-certificate
spec:
  domains:
    - grocerybrasil.com
    - api.grocerybrasil.com
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: text-search
  annotations:
    kubernetes.io/ingress.global-static-ip-name: api
    networking.gke.io/managed-certificates: grocery-brasil-app-https-certificate
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.allow-http: "false"
spec:
  backend:
    serviceName: text-search
    servicePort: 8080